version: '3'

services:
  
  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "3001:3001"
    
  app:
    build: ./app
    depends_on:
      - api
    ports:
      - "80:80"
    links:
      - api